name: JustAttribute
main: com.sakuragame.eternal.justattribute.JustAttribute
version: ${project.version}
author: 'Megumi'
api-version: '1.13'
depend:
  - DataManager
  - MegumiLib
  - Zaphkiel
  - DragonCore
  - JustLevel

commands:
  jattribute:
    aliases: [attribute, attr]
    description: show all command