name: JustAttribute
main: com.sakuragame.eternal.justattribute.JustAttribute
version: ${project.version}
author: 'justwei'
api-version: '1.13'
depend:
  - MegumiLib
  - DataManager
  - NBTAPI
  - JustLevel
  - JustMessage
  - Zaphkiel
  - DragonCore
  - MythicMobs
softdepend:
  - PlayerSQL

commands:
  jattribute:
    aliases: [attribute, attr]
    description: show all command